# Generated by Django 2.0.5 on 2018-06-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='website_submitter',
            field=models.BooleanField(default=True),
        ),
    ]
